version: '3.7'
services:
  node:
    build: .
    ports:
      - '80:80'
    depends_on:
      - db
    networks:
      - webnet
    environment:
      - NODE_ENV=production
      - PORT=80
      - SEQUELIZE_PASSWORD=password
      - SEQUELIZE_USERNAME=root
      - SEQUELIZE_DATABASE=todolist
      - SEQUELIZE_HOST=db
  db:
    image: mysql:5.7.29
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    networks:
      - webnet
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
networks:
  webnet:
    driver: bridge
