version: "3.7"
services:
  node:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - webnet
    environment:
      - NODE_ENV=production
      - PORT=80
      - SEQUELIZE_PASSWORD=password
      - SEQUELIZE_USERNAME=root
      - SEQUELIZE_DATABASE=todolist
      - SEQUELIZE_HOST=db
  db:
    image: mysql:5.7.29
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    networks:
      - webnet
networks:
  webnet:
    driver: bridge
